// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIMOfJSYxYVc3l1HVBvGMeaT6mxRFJtq4',
    appId: '1:910806227774:web:473d2622f586ee304baa6f',
    messagingSenderId: '910806227774',
    projectId: 'todo-flutterapp',
    authDomain: 'todo-flutterapp.firebaseapp.com',
    storageBucket: 'todo-flutterapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKG4siYyZggig76W5UjXZr39bv9S0NhHo',
    appId: '1:910806227774:android:6a70986e2d187a534baa6f',
    messagingSenderId: '910806227774',
    projectId: 'todo-flutterapp',
    storageBucket: 'todo-flutterapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5tQrjEoUMhbPpm5MhPnm4CMHhLT-acUs',
    appId: '1:910806227774:ios:062d8a6c7c1abf184baa6f',
    messagingSenderId: '910806227774',
    projectId: 'todo-flutterapp',
    storageBucket: 'todo-flutterapp.appspot.com',
    iosClientId: '910806227774-7moeasjgq19qj7ep8oe87aetp3dh3t77.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5tQrjEoUMhbPpm5MhPnm4CMHhLT-acUs',
    appId: '1:910806227774:ios:062d8a6c7c1abf184baa6f',
    messagingSenderId: '910806227774',
    projectId: 'todo-flutterapp',
    storageBucket: 'todo-flutterapp.appspot.com',
    iosClientId: '910806227774-7moeasjgq19qj7ep8oe87aetp3dh3t77.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
